name: 'dart_mobile_catalog'
version: 0.0.1
description: Full featured multi-user mobile catalog web app.
author: jnoortheen <jnoortheen@gmail.com>
homepage: https://github.com/jnoortheen/dart-mobile-catalog

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  redstone: any
  test: any
  redstone_mapper: any
  redstone_mapper_mongo: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
- redstone_mapper
